# Generated by Django 3.2.9 on 2021-12-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wish_list',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
