# Generated by Django 3.2.9 on 2021-12-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('imageOne', models.CharField(max_length=1000)),
                ('imageTwo', models.CharField(max_length=1000)),
            ],
        ),
    ]
