# Generated by Django 3.2.9 on 2021-12-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_one', models.CharField(max_length=1000)),
                ('image_two', models.CharField(max_length=1000)),
                ('brand', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('colour', models.CharField(max_length=100)),
            ],
        ),
    ]
